In [5]:
import math
from geopy import distance


def gcj02towgs84(lng, lat):
    """
    GCJ02(火星坐标系)转GPS84
    :param lng:火星坐标系的经度
    :param lat:火星坐标系纬度
    :return:
    """
    pi = 3.1415926535897932384626
    ee = 0.00669342162296594323  # 扁率
    a = 6378245.0  # 长半轴
    dlat = transformlat(lng - 105.0, lat - 35.0)
    dlng = transformlng(lng - 105.0, lat - 35.0)
    radlat = lat / 180.0 * pi
    magic = math.sin(radlat)
    magic = 1 - ee * magic * magic
    sqrtmagic = math.sqrt(magic)
    dlat = (dlat * 180.0) / ((a * (1 - ee)) / (magic * sqrtmagic) * pi)
    dlng = (dlng * 180.0) / (a / sqrtmagic * math.cos(radlat) * pi)
    mglat = lat + dlat
    mglng = lng + dlng
    return [lng * 2 - mglng, lat * 2 - mglat]

def wgs84togcj02(lng, lat):
    """
    WGS84转GCJ02(火星坐标系)
    :param lng:WGS84坐标系的经度
    :param lat:WGS84坐标系的纬度
    :return:
    """
    pi = 3.1415926535897932384626
    ee = 0.00669342162296594323  # 扁率
    a = 6378245.0  # 长半轴
    dlat = transformlat(lng - 105.0, lat - 35.0)
    dlng = transformlng(lng - 105.0, lat - 35.0)
    radlat = lat / 180.0 * pi
    magic = math.sin(radlat)
    magic = 1 - ee * magic * magic
    sqrtmagic = math.sqrt(magic)
    dlat = (dlat * 180.0) / ((a * (1 - ee)) / (magic * sqrtmagic) * pi)
    dlng = (dlng * 180.0) / (a / sqrtmagic * math.cos(radlat) * pi)
    mglat = lat + dlat
    mglng = lng + dlng
    return [mglng, mglat]


def transformlat(lng, lat):
    pi = 3.1415926535897932384626
    ret = -100.0 + 2.0 * lng + 3.0 * lat + 0.2 * lat * lat + \
        0.1 * lng * lat + 0.2 * math.sqrt(math.fabs(lng))
    ret += (20.0 * math.sin(6.0 * lng * pi) + 20.0 *
            math.sin(2.0 * lng * pi)) * 2.0 / 3.0
    ret += (20.0 * math.sin(lat * pi) + 40.0 *
            math.sin(lat / 3.0 * pi)) * 2.0 / 3.0
    ret += (160.0 * math.sin(lat / 12.0 * pi) + 320 *
            math.sin(lat * pi / 30.0)) * 2.0 / 3.0
    return ret


def transformlng(lng, lat):
    pi = 3.1415926535897932384626
    ret = 300.0 + lng + 2.0 * lat + 0.1 * lng * lng + \
        0.1 * lng * lat + 0.1 * math.sqrt(math.fabs(lng))
    ret += (20.0 * math.sin(6.0 * lng * pi) + 20.0 *
            math.sin(2.0 * lng * pi)) * 2.0 / 3.0
    ret += (20.0 * math.sin(lng * pi) + 40.0 *
            math.sin(lng / 3.0 * pi)) * 2.0 / 3.0
    ret += (150.0 * math.sin(lng / 12.0 * pi) + 300.0 *
            math.sin(lng / 30.0 * pi)) * 2.0 / 3.0
    return ret


#  求两个坐标之间的球面距离
#  输入(lat1, lng1),(lat2, lng2)  例子:36.03071, 119.370695, 36.028785, 119.36689
def geo_distance(P1_lat, P1_lng, P2_lat, P2_lng):
    length = distance.great_circle((P1_lat, P1_lng), (P2_lat, P2_lng)).m
    return length

In [62]:
from requests_html import HTMLSession
import json
import utils
import transCoordinateSystem
import pandas as pd
# 通过接口调用
# token = "..."
# coordinate=[114.21892734521,29.575429778924]
# url = 'http://api.map.baidu.com/geoconv/v1/?coords='\
#     +str(coordinate[0])+','+str(coordinate[1])+'&from=1&to=3&ak='+ token
# session = HTMLSession()
# rq = session.get(url)
# result = json.loads(rq.html.html)
# print(result)
data = pd.read_excel('D:/data/挖掘运输热点数据/6.29新的分类数据/人工标注-新增.xlsx')


coordinate=[122.37002, 36.93753]
modify_co = utils.wgs84togcj02(coordinate[0], coordinate[1])
print(modify_co)

[122.37495981939439, 36.9382494551862]

In [67]:
coordinate=[121.16882, 37.35455]
modify_co = utils.wgs84togcj02(coordinate[0], coordinate[1])
print(modify_co)

[121.17394163580984, 37.35543840217508]

In [61]:
data.head(2)

,原始地点ID,type(运输终点/采购地点）,left_up_longitude,left_up_latitude,right_down_longitude,right_down_latitude
0,P000000000282,运输终点,122.37002,36.93753,122.37622,36.93393
1,P000000000283,休息区,121.16882,37.35455,121.17062,37.35349

In [6]:
def wgs84togaode(arrLike, lng, lat):
    """
    WGS84转GCJ02(火星坐标系)
    :param lng:WGS84坐标系的经度
    :param lat:WGS84坐标系的纬度
    :return:
    """
    pi = 3.1415926535897932384626
    ee = 0.00669342162296594323  # 扁率
    a = 6378245.0  # 长半轴
    dlat = transformlat(arrLike[lng] - 105.0, arrLike[lat] - 35.0)
    dlng = transformlng(arrLike[lng] - 105.0, arrLike[lat] - 35.0)
    radlat = arrLike[lat] / 180.0 * pi
    magic = math.sin(radlat)
    magic = 1 - ee * magic * magic
    sqrtmagic = math.sqrt(magic)
    dlat = (dlat * 180.0) / ((a * (1 - ee)) / (magic * sqrtmagic) * pi)
    dlng = (dlng * 180.0) / (a / sqrtmagic * math.cos(radlat) * pi)
    mglat = arrLike[lat] + dlat
    mglng = arrLike[lng] + dlng
    return [mglng, mglat]
coor_left = data.apply(wgs84togaode, axis=1, args=('left_up_longitude', 'left_up_latitude'))
coor_right = data.apply(wgs84togaode, axis=1, args=('right_down_longitude', 'right_down_latitude'))
coor_left = pd.DataFrame(coor_left)
coor_right = pd.DataFrame(coor_right)

In [7]:
data['gaode_left_up_longitude'] = coor_left[0].str[0]
data['gaode_left_up_latitude'] = coor_left[0].str[1]
data['gaode_right_down_longitude'] = coor_right[0].str[0]
data['gaode_right_down_latitude'] = coor_right[0].str[1]
data.head()

,原始地点ID,type(运输终点/采购地点等）,left_up_longitude,left_up_latitude,right_down_longitude,right_down_latitude,标注人,gaode_left_up_longitude,gaode_left_up_latitude,gaode_right_down_longitude,gaode_right_down_latitude
0,P000021035,运输终点,119.556140,35.376150,119.558230,35.374190,石玥,119.561467,35.375761,119.563551,35.373795
1,P000018732,运输终点,119.503460,35.347070,119.504381,35.346130,石玥,119.508975,35.346790,119.509892,35.345846
2,P000012504,运输终点,119.456650,35.332130,119.459560,35.329980,石玥,119.462342,35.331966,119.465242,35.329807
3,P000014334,运输终点,119.447210,35.363980,119.451380,35.361910,石玥,119.452933,35.363864,119.457091,35.361784
4,P000015111,运输终点,119.426614,35.384286,119.427807,35.383292,石玥,119.432385,35.384219,119.433575,35.383223

In [3]:
import pandas as pd
data = pd.read_csv('D:/data/挖掘运输热点数据/6.29新的分类数据/人工标注整合20210701爬取.csv')

In [4]:
data.head()

,原始地点ID,type(运输终点/采购地点等）,left_up_longitude,left_up_latitude,right_down_longitude,right_down_latitude,标注人
0,P000021035,运输终点,119.556140,35.376150,119.558230,35.374190,石玥
1,P000018732,运输终点,119.503460,35.347070,119.504381,35.346130,石玥
2,P000012504,运输终点,119.456650,35.332130,119.459560,35.329980,石玥
3,P000014334,运输终点,119.447210,35.363980,119.451380,35.361910,石玥
4,P000015111,运输终点,119.426614,35.384286,119.427807,35.383292,石玥

In [8]:
data.to_csv('D:/data/挖掘运输热点数据/6.29新的分类数据/人工标注整合0702.csv')

In [17]:
data = pd.read_excel('D:/data/挖掘运输热点数据/6.29新的分类数据/人工标注整合0702.xlsx')

In [18]:
data.head()

,原始地点ID,type(运输终点/采购地点等),left_up_longitude,left_up_latitude,right_down_longitude,right_down_latitude,标注人,gaode_left_up_longitude,gaode_left_up_latitude,gaode_right_down_longitude,gaode_right_down_latitude,cen_longitude,cen_latitude
0,P000021035,运输终点,119.556140,35.376150,119.558230,35.374190,石玥,119.561467,35.375761,119.563551,35.373795,119.562509,35.374778
1,P000018732,运输终点,119.503460,35.347070,119.504381,35.346130,石玥,119.508975,35.346790,119.509892,35.345846,119.509434,35.346318
2,P000012504,运输终点,119.456650,35.332130,119.459560,35.329980,石玥,119.462342,35.331966,119.465242,35.329807,119.463792,35.330886
3,P000014334,运输终点,119.447210,35.363980,119.451380,35.361910,石玥,119.452933,35.363864,119.457091,35.361784,119.455012,35.362824
4,P000015111,运输终点,119.426614,35.384286,119.427807,35.383292,石玥,119.432385,35.384219,119.433576,35.383223,119.432980,35.383721